- include_tasks: validate-parameters.yml

- name: Check if {{ stack_name }} stack exists
  command: "openstack stack show {{ stack_name }}"
  ignore_errors: yes
  register: stack_check

- name: Create heat stack {{ stack_name }}
  stack_create:
    name: "{{ stack_name }}"
    template: "{{ heat_template_path }}"
    parameters:
      domain_name: "{{ domain_name }}"
      external_network: "{{ external_network }}"
      service_subnet_cidr: "{{ service_subnet_cidr }}"
      router_id: "{{ router_id }}"
      ssh_key_name: "{{ ssh_key_name }}"
      dns_forwarders: "{{ dns_forwarders }}"
      image: "{{ image }}"
      bastion_flavor: "{{ bastion_flavor }}"
      master_flavor: "{{ master_flavor }}"
      infra_flavor: "{{ infra_flavor }}"
      node_flavor: "{{ node_flavor }}"

      master_count: "{{ master_count }}"
      infra_count: "{{ infra_count }}"
      node_count: "{{ node_count }}"
      master_server_group_policies: "{{ master_server_group_policies }}"
      infra_server_group_policies: "{{ infra_server_group_policies }}"
      node_server_group_policies: "{{ node_server_group_policies }}"
  register: stack_output
  when: stack_check.rc != 0

- name: Register stack output
  command: >
    openstack stack output show -f json -c output_value
    {{ stack_name }} ip_address
  register: stack_output_raw

- set_fact:
    #stack_output: "{{ stack_output_raw.stdout|from_json }}"
    stack_output: "{{ stack_output_raw }}"

#- name: Update openshift subnet in inventory file
#  lineinfile:
#    path: /etc/selinux/config
#    regexp: '^openshift_cloudprovider_openstack_lb_subnet_id='
#    line: 'openshift_cloudprovider_openstack_lb_subnet_id={{ osp_subnet_id }}'
#  vars:
#    ansible_connection: local

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
