- name: Validate masters
  assert:
    that:
      - (master_count == 1) or (master_count == 3)
    msg: "Master count is currently {{ master_count }} but must be 1 or 3"

- name: Validate infras
  assert:
    that:
      - (infra_count >= 1 ) 
      - (infra_count <= 3)
    msg: "Infra count s currently {{ infra_count }} but must be between 1 and 3"

- name: Validate infra private auth shard
  assert:
    that:
      - (infra_shard_private_auth_count >= 1 ) 
      - (infra_shard_private_auth_count <= 2)
    msg: "Infra private auth shard count currently {{ infra_shard_private_auth_count }} but must be between 1 and 2"

- name: Validate infra private unauth shard
  assert:
    that:
      - (infra_shard_private_auth_count >= 1 ) 
      - (infra_shard_private_auth_count <= 2)
    msg: "Infra private auth shard count currently {{ infra_shard_private_auth_count }} but must be between 1 and 2"

- name: Validate nodes
  assert:
    that:
      - (node_count >= 0 ) 
    msg: "Node count {{ node_count }} must be >= 0"

- name: Validate nodes
  assert:
    that:
      - (node_shard_private_auth_count >= 0 ) 
    msg: "Node count {{ node_shard_private_auth_count }} must be >= 0"    

- name: Validate nodes
  assert:
    that:
      - (node_shard_private_unauth_count >= 0 ) 
    msg: "Node count {{ node_shard_private_unauth_count }} must be >= 0"    

- name: Validate OpenShift HA
  assert:
    that:
      - (master_count == 3) and (infra_count > 1)
    msg: "OpenShift HA requires 3 masters and at least 2 infra nodes"
  when: openshift_ha

#- name: Validate Registry HA
#  assert:
#    that:
#      - (registry_replicas > 1 )
#    msg: "OpenShift HA requires at least 2 registry replicas"
#  when: openshift_ha
