- name: Setup OpenShift Enterprise inventory file
  template:
    src: templates/openshift-inventory-enterprise.j2
    dest: /home/{{ ssh_user }}/openshift-inventory
    owner: root
    group: root
    mode: 0755
  when: openshift_deployment == "openshift-enterprise"

- name: Setup OpenShift OKD inventory file
  template:
    src: templates/openshift-inventory-origin.j2
    dest: /home/{{ ssh_user }}/openshift-inventory
    owner: root
    group: root
    mode: 0755
  when: openshift_deployment == "origin"

- name: Configure masters dynamically
  lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
    line="{{ item }} openshift_hostname={{ item }} server_type=\"master\""
    insertafter="^#?\[masters\]"
  with_items: "{{ groups['masters'] }}"

- name: Configure etcd nodes dynamically
  lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
    line="{{ item }} openshift_hostname={{ item }} server_type=\"etcd\""
    insertafter="^#?\[etcd\]"
  with_items: "{{ groups['masters'] }}"

- name: Configure master nodes dynamically
  lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
    line="{{ item }} openshift_hostname={{ item }} openshift_schedulable=True openshift_node_group_name='node-config-master'"
    insertafter="^#?\[nodes\]"
  with_items: "{{ groups['masters'] }}"

- name: Configure infra nodes dynamically
  lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
    line="{{ item }} openshift_hostname={{ item }} openshift_schedulable=True openshift_node_group_name='node-config-infra'"
    insertafter="^#?{{ master_regex }}"
  with_items: "{{ groups['infras'] }}"

- name: Configure app nodes dynamically
  lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
    line="{{ item }} openshift_hostname={{ item }} openshift_schedulable=True openshift_node_group_name='node-config-compute'"
    insertafter="^#?{{ infra_regex }}"
  with_items: "{{ groups['nodes'] }}"
