#!/usr/bin/env ansible-playbook
---
- name: Deploy the OpenShift Cluster Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
  - name: Include vars.yml
    include_vars:
      file: vars.yml

  - import_role:
      name: osp-inventory

- name: Configure local RHN repos on Bastion
  hosts: bastion
  become: true

  tasks:
  - name: Include vars.yml
    include_vars:
      file: vars.yml

  - name: Set ansible_ssh_private_key_file
    set_fact:
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"

  - import_role:
      name: bastion-repo
    when: openshift_deployment == "openshift-enterprise"
