---
- name: Inventory OpenShift Nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: http://{{ openstack_ip }}:5000/v3
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3

  tasks:
  - import_role:
      name: osp-inventory

- name: Setup All OpenShift Nodes
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - import_role:
      name: all-prep

- name: Setup All OpenShift Nodes
  hosts: openshift
  gather_facts: true
  become: true

  tasks:
  - import_role:
      name: docker-prep

- name: Configure OpenShift inventory file
  hosts: bastion
  gather_facts: true
  become: true

  tasks:
  - import_role:
      name: ocp-inventory
