- name: Authenticate to OpenShift via Token
  shell: oc login {{ url }} --token {{ token }}

- name: Create OpenShift Project
  shell: oc new-project {{ project }}

- name: Add users and roles to project
  shell: oc policy add-role-to-user {{ role }} {{ user }} -n {{ project }}
