- name: Enable bastion specific repos (redhat)
  command: "subscription-manager repos --enable={{item}}"
  retries: 5
  delay: 5
  with_items: "{{repos_bastion}}"
  when: openshift_deployment == "openshift-enterprise" and not rhn_local_repo

- name: Enable correct local repos
  yum_repository:
    name: "{{item}}"
    description: "{{item}}"
    file: openshift
    baseurl: "{{rhn_local_repo_base_url}}/{{item}}"
    gpgcheck: no
  with_items:
    - "{{repos_bastion}}"
    - "{{repos}}"
  when: openshift_deployment == "openshift-enterprise" and rhn_local_repo

- name: Enable bastion specific repos (centos)
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{origin_repos_bastion}}"
  when: openshift_deployment == "origin"

- name: Ensure that required packages are installed on bastion
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Perform yum update
  yum:
    name=*
    state=latest

- name: Install required openstack packages for bastion (redhat)
  yum:
    name: "{{item}}"
    state: installed
    disablerepo: rhel-7-fast-datapath-rpms
    disablerepo: rhel-7-server-ose-{{ openshift_version }}-rpms
  with_items: "{{packages_bastion_openstack}}"
  when: openshift_deployment == "openshift-enterprise"

- name: Install required openstack packages for bastion (centos)
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages_bastion_openstack}}"
  when: openshift_deployment == "origin"

- name: Install required installer packages for bastion (redhat)
  yum:
    name: "{{item}}"
    state: installed
    disablerepo: rhel-7-server-openstack-{{ openstack_version }}-tools-rpms
  with_items: "{{ packages_bastion_openshift }}"
  when: openshift_deployment == "openshift-enterprise"

- name: Install required installer packages for bastion (centos)
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages_bastion_origin}}"
  when: openshift_deployment == "origin"

- name: Disable epel repository (centos)
  yum_repository:
    name: epel
    baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    description: "EPEL"
    enabled: no
  when: openshift_deployment == "origin"

- name: Clone OKD repository
  git:
    repo: 'https://github.com/openshift/openshift-ansible'
    dest: /home/{{ ssh_user }}/openshift-ansible
    version: release-{{ openshift_version }}
  when: openshift_deployment == "origin"

- name: Create ~/.ssh/ directory
  become: false
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Copy OpenStack ssh key to bastion
  become: false
  copy:
    src: "{{ ssh_key_path }}"
    dest: ~/.ssh/id_rsa
    mode: 0400
    owner: "{{ ssh_user }}"

- name: Copy playbooks to bastion
  copy:
    src: "{{ playbook_dir }}"
    dest: /home/{{ ssh_user }}
    directory_mode: 0755
    mode: 0755
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: Copy ansible.cfg to user home dir
  copy:
    src: "{{ playbook_dir }}/ansible.cfg"
    dest: /home/{{ ssh_user }}/.ansible.cfg
    mode: 0644
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
