- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Enable correct local repos
  yum_repository:
    name: "{{item}}"
    description: "{{item}}"
    file: openshift
    baseurl: "{{rhn_local_repo_base_url}}/{{item}}"
    gpgcheck: no
  with_items: "{{repos}}"
  when: openshift_deployment == "openshift-enterprise" and rhn_local_repo

- name: Ensure that required packages are present on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Install Required Packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages}}"

- name: Ensure NetworkManager is enabled and started
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
