- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Ensure that required packages are present on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Install Required Packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages}}"

- name: Ensure NetworkManager is enabled and started
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
