- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: copy certificate authority to trusted ca path of the os
  copy:
    src: ~/cacert.pem
    dest: /etc/pki/ca-trust/source/anchors
  sudo: yes
  when: bastion_repo

- name: update trusted ca redhat
  shell: /bin/update-ca-trust
  when: bastion_repo

- name: Set correct repo ip if bastion repo is enabled
  set_fact:
    repo_base_url: "http://{{hostvars['bastion']['ansible_default_ipv4']['address'] }}/repo"
  when: bastion_repo

- name: Set correct repo ip if bastion repo is not enabled
  set_fact:
    repo_base_url: "{{rhn_local_repo_base_url}}"
  when: not bastion_repo

- name: Enable correct local repos
  yum_repository:
    name: "{{item}}"
    description: "{{item}}"
    file: openshift
    baseurl: "{{repo_base_url}}/{{item}}"
    gpgcheck: no
  with_items: "{{repos}}"
  when: openshift_deployment == "openshift-enterprise" and rhn_local_repo

- name: Ensure that required packages are present on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Install Required Packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages}}"

- name: Ensure NetworkManager is enabled and started
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
