- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: check if host already registered
  command: subscription-manager list --available --match-installed --matches=*Openshift* --pool-only
  register: subs_result
  failed_when: false
  changed_when: "'This system is not yet registered' in subs_result.stderr"

- name: Subscribe to Red Hat subscription using username
  redhat_subscription:
    state: present
    username: "{{ rhn_username_or_org_id }}"
    password: "{{ rhn_password_or_activation_key }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe_user
  retries: 5
  delay: 5
  when: subscription_use_username == True and subs_result.changed

- name: Subscribe to Red Hat using activation key
  redhat_subscription:
    state: present
    org_id: "{{ rhn_username_or_org_id }}"
    activationkey: "{{ rhn_password_or_activation_key }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe_activation_key
  retries: 5
  delay: 5
  when: subscription_use_username == False and subs_result.changed

- debug:
    msg: "username subscription {{ subscribe_user.changed }}"

- debug:
    msg: "activation key subscription {{ subscribe_activation_key.changed }}"

- name: Disable all repos
  shell: |
    subscription-manager repos --disable=*
  retries: 5
  delay: 5
  when: subscribe.changed

- name: Enable correct repos
  command: "subscription-manager repos --enable={{item}}"
  when: subscribe.changed
  retries: 5
  delay: 5
  with_items: "{{repos}}"

- name: Ensure that required packages are present on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Install Required Packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages}}"
