- name: Check whether the stack exists already
  command: "openstack stack show {{ stack_name }}"
  register: stack_check

- name: Register stack output
  command: >
    openstack stack output show -f json -c output_value
    {{ stack_name }} ip_address
  register: stack_output_raw

- name: print debug
  debug:
      msg: "here {{ stack_output_raw.stdout }}"

- set_fact:
    stack_output: "{{ (stack_output_raw.stdout|from_json).output_value }}"

- name: Add the bastion to the inventory
  add_host:
    name: "{{ stack_output.bastion.name }}"
    groups: bastion,all
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ stack_output.bastion.address }}"

- name: Add the masters to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: masters,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
    lb_master: "{{ stack_output.lb_master.address }}"
  with_items: "{{ stack_output.masters }}"

- name: Add the infras to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: infras,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
    lb_infra: "{{ stack_output.lb_infra.address }}"
  with_items: "{{ stack_output.infras }}"

- name: Add the priv auth infras to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: infras,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
    lb_infra: "{{ stack_output.lbaas_infras_priv_auth.address }}"
  with_items: "{{ stack_output.infras_priv_auth_shard }}"

- name: Add the priv unauth infras to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: infras,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
    lb_infra: "{{ stack_output.lbaas_infras_priv_unauth.address }}"
  with_items: "{{ stack_output.infras_priv_unauth_shard }}"

- name: Add the nodes to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: nodes,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
  with_items: "{{ stack_output.nodes }}"

- name: Add the priv auth nodes to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: nodes,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
  with_items: "{{ stack_output.nodes_priv_auth_shard }}"

- name: Add the priv unauth nodes to the inventory
  add_host:
    name: "{{ item.name }}"
    groups: nodes,all,openshift
    zone: "{{ domain_name }}"
    domain_name: "{{ domain_name }}"
    contact: "{{ contact }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_host: "{{ item.address }}"
  with_items: "{{ stack_output.nodes_priv_unauth_shard }}"
