---
- name: Deploy the OpenShift Cluster Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - import_role:
      name: osp-stack-create
  - import_role:
      name: osp-inventory

  - name: Get OpenShift subnet id
    command: >
      openstack subnet show osp-subnet -c id -f value
    register: osp_subnet_id

  - name: Update OpenShift inventory template with subnet id
    lineinfile:
      path: roles/ocp-inventory/templates/openshift-inventory.j2
      regexp: '^openshift_cloudprovider_openstack_lb_subnet_id='
      line: 'openshift_cloudprovider_openstack_lb_subnet_id={{ osp_subnet_id.stdout }}'

- name: Configure OpenStack Client on Bastion
  hosts: bastion
  become: true
  vars_files:
    - vars.yml

  tasks:
  - import_role:
      name: bastion-prep

