---
- name: Deploy the OpenShift Cluster Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - import_role:
      name: osp-stack-create
  - import_role:
      name: osp-inventory

- name: Configure OpenStack Client on Bastion
  hosts: bastion
  become: true
  vars_files:
    - vars.yml

  tasks:
  - import_role:
      name: bastion-prep

