---
- import_playbook: validate-parameters.yml

- name: Deploy the OpenShift Cluster Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:

    - name: Check whether the stack exists already
      command: "openstack stack show {{ stack_name }}"
      ignore_errors: yes
      register: stack_check

    - name: Create the Heat Stack
      os_stack:
        name: "{{ stack_name }}"
        template: ../heat/openshift.yaml
        parameters:
          domain_name: "{{ domain_name }}"
          external_network: "{{ external_network }}"
          ssh_key_name: "{{ ssh_key_name }}"
          dns_forwarders: "{{ dns_forwarders }}"
          image: "{{ image }}"
          bastion_flavor: "{{ bastion_flavor }}"
          master_flavor: "{{ master_flavor }}"
          infra_flavor: "{{ infra_flavor }}"
          node_flavor: "{{ node_flavor }}"

          master_count: "{{ master_count }}"
          infra_count: "{{ infra_count }}"
          node_count: "{{ node_count }}"
          #master_server_group_policies: "{{ master_server_group_policies }}"
          #master_server_group_policies: affinity
          #infra_server_group_policies: "{{ infra_server_group_policies }}"
          #infra_server_group_policies: affinity
          #node_server_group_policies: "{{ node_server_group_policies }}"
          #node_server_group_policies: affinity
      register: stack_output
      when: stack_check.rc != 0

    - name: Register stack output
      command: >
        openstack stack output show -f value -c output_value
        {{ stack_name }} ip_address
      register: stack_output_raw

    - set_fact:
        stack_output: "{{ stack_output_raw.stdout|from_json }}"

    - name: Add the bastion to the inventory
      add_host:
        name: "{{ stack_output.bastion.address }}"
        groups: bastion
        zone: "{{ domain_name }}"
        domain_name: "{{ domain_name }}"
        contact: "{{ contact }}"
        ansible_user: "{{ ssh_user }}"

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local

- name: Configure OpenStack Client on Bastion
  hosts: bastion
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Copy hosts file from template
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    - name: check if host already registered
      command: subscription-manager list --available --match-installed --matches=*Openshift* --pool-only
      register: subs_result
      failed_when: false
      changed_when: "'This system is not yet registered' in subs_result.stderr"

    - name: Register hosts
      command: subscription-manager register --username={{ rhn_username }} --password={{ rhn_password }}
      retries: 5
      delay: 5
      when: subs_result.changed

    - name: Check Red Hat subscription
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool: "{{ rhn_pool }}"
        #force_register: yes
      register: subscribe
      retries: 5
      delay: 5
    - debug:
        msg: "{{subscribe}}"
    - name: Disable all repos
      shell: |
        subscription-manager repos --disable=*
      retries: 5
      delay: 5
      when: subscribe.changed

    - name: Enable correct repos
      command: "subscription-manager repos --enable={{item}}"
      when: subscribe.changed
      retries: 5
      delay: 5
      with_items: "{{repos}}"

    - name: Enable bastion specific repos
      command: "subscription-manager repos --enable={{item}}"
      retries: 5
      delay: 5
      with_items: "{{repos_bastion}}"

    - name: Ensure that required packages are present on target hosts
      yum:
        name: "{{item}}"
        state: latest
      retries: 5
      delay: 5
      with_items: "{{packages}}"

    - name: Install Required Packages
      yum: 
        name: "{{item}}"
        state: installed
      with_items: "{{packages}}"

    - name: Install required openstack packages for bastion
      yum:
        name: "{{item}}"
        state: installed
        disablerepo: rhel-7-fast-datapath-rpms
        disablerepo: rhel-7-server-ose-3.7-rpms
      with_items: "{{packages_bastion_openstack}}"

    - name: Install required openshift packages for bastion
      yum:
        name: "{{item}}"
        state: installed
        disablerepo: rhel-7-server-openstack-12-tools-rpms
      with_items: "{{packages_bastion_openshift}}"

    - name: Copy OpenStack Credentials to Bastion
      copy:
        src: /root/keystonerc_admin
        dest: /home/cloud-user/keystonerc_admin
        mode: 0755
        owner: "{{ ssh_user }}"

    - name: Copy OpenStack ssh key to bastion
      copy:
        src: /root/admin.pem
        dest: /home/cloud-user/admin.pem
        mode: 0400
        owner: "{{ ssh_user }}"

    - name: Setup OpenShift inventory file
      template:
        src: templates/openshift-inventory.j2
        dest: /home/{{ ssh_user }}/openshift-inventory
        owner: root
        group: root
        mode: 0755

    - name: Copy playbooks to bastion
      copy:
        src: ../playbooks
        dest: /home/{{ ssh_user }}
        directory_mode: 0755
        mode: 0755
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
