---
- name: Setup All OpenShift Nodes
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Build hosts file with all hosts
      lineinfile: 
        dest=templates/hosts.j2
        line="{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}" 
        state=present
      when: ansible_default_ipv4.address is defined
      delegate_to: localhost

    - name: Copy hosts file from template
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    - name: check if host already registered
      command: subscription-manager list --available --match-installed --matches=*Openshift* --pool-only
      register: subs_result
      failed_when: false
      changed_when: "'This system is not yet registered' in subs_result.stderr"

    - name: Register hosts
      command: subscription-manager register --username={{ rhn_username }} --password={{ rhn_password }}
      retries: 5
      delay: 5
      when: subs_result.changed

    - name: Check Red Hat subscription
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool: "{{ rhn_pool }}"
        #force_register: yes
      register: subscribe
      retries: 5
      delay: 5
    - debug:
        msg: "{{subscribe}}"
    - name: Disable all repos
      shell: |
        subscription-manager repos --disable=*
      retries: 5
      delay: 5
      when: subscribe.changed
    - name: Enable correct repos
      command: "subscription-manager repos --enable={{item}}"
      when: subscribe.changed
      retries: 5
      delay: 5
      with_items: "{{repos}}"

    - name: Ensure that required packages are present on target hosts
      yum:
        name: "{{item}}"
        state: latest
      retries: 5
      delay: 5
      with_items: "{{packages}}"

    - name: Install Required Packages
      yum: 
        name: "{{item}}"
        state: installed
      with_items: "{{packages}}"

- name: Setup All OpenShift Nodes
  hosts: openshift
  gather_facts: true
  become: true
  vars_files:
    - vars.yml
  tasks:

    - name: Install Docker {{ docker_version }}
      package:
        name: docker-{{ docker_version }}
        state: installed

    - name: Perform yum update
      yum: 
        name=* 
        state=latest

    - name: Update /etc/sysconfig/docker
      lineinfile: 
        dest: /etc/sysconfig/docker
        regexp: '^(.*)OPTIONS(.*)$' 
        line: "OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled --log-driver=journald'"
        backrefs: yes

    - name: Configure Docker Storage
      blockinfile: |
        dest=/etc/sysconfig/docker-storage-setup 
        backup=yes
        content="DEVS=/dev/vdb
            VG=docker-vg" 

    - name: Run Docker Storage Setup
      command: docker-storage-setup

    - name: Enable and Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

- name: Configure OpenShift inventory file
  hosts: bastion
  gather_facts: true
  become: true
  vars_files:
    - vars.yml
  tasks:

    - name: Configure nodes dynamically
      lineinfile: dest=/home/{{ ssh_user }}/openshift-inventory
        line="{{ item }}.{{ domain_name }} openshift_schedulable=True openshift_node_labels=\"{'region'{{ ":" }} 'primary', 'zone'{{ ":" }} 'test', 'fluentd'{{ ":" }} 'true'}\""
        insertafter="^#?infra0.ocp3.lab"
      with_items: "{{ groups['nodes'] }}"
