---
- name: Validate Parameters
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:

    - name: Validate masters
      assert:
        that:
          - (master_count == 1) or (master_count == 3)
        msg: "Master count is currently {{ master_count }} but must be 1 or 3"

    - name: Validate infras
      assert:
        that:
          - (infra_count >= 1 ) 
          - (infra_count <= 3)
        msg: "Infra count s currently {{ infra_count }} but must be between 1 and 3"

    - name: Validate nodes
      assert:
        that:
          - (node_count >= 1 ) 
        msg: "Node count {{ node_count }} must be >= 1"
